/**
 * translate.js — Full translation lookup helper
 * Languages: English (en), Hindi (hi), Telugu (te), Spanish (es)
 */
const TRANSLATIONS = {
    en: {
        // General
        welcome: 'Welcome',
        logout: 'Logout',
        login: 'Login',
        signin: 'Sign In',
        register: 'Register',
        home: 'Home',
        back: 'Back',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        loading: 'Loading…',
        error: 'Error',
        success: 'Success',
        pending: 'Pending',
        resolved: 'Resolved',
        status: 'Status',
        author: 'Author',
        category: 'Category',
        description: 'Description',
        previous: 'Previous',
        next: 'Next',
        search: 'Search',

        // Landing Page
        newEra: 'A NEW ERA OF FARMING',
        heroHeadline: 'EMPOWERING FARMERS FOR A SUSTAINABLE FUTURE',
        heroSubtext1: 'Bridging the gap between farmers, experts, financiers, and consumers. Cultivate success',
        heroSubtext2: 'and resilience through cutting-edge knowledge, innovation, and community.',
        getStarted: 'Get Started',
        joinAsFarmer: 'Join as Farmer',
        exploreFeatures: 'EXPLORE FEATURES',
        feature1Title: 'CROP DISEASE DETECTION',
        feature1Desc: 'Upload photos of your crops. Our AI-driven image analysis provides instant diagnosis and remedies, later reviewed by verified agricultural experts.',
        feature2Title: 'DIRECT MARKETPLACE',
        feature2Desc: 'Bypass the middleman. Sell your produce directly to consumers or business buyers at transparent, self-assigned prices for maximum profitability.',
        feature3Title: 'FINANCIAL SUPPORT',
        feature3Desc: 'Access tailored loan options and financial assistance from registered financiers. Submit requests effortlessly and track approvals in real-time.',
        feature4Title: 'REAL-TIME INSIGHTS',
        feature4Desc: 'Stay ahead of unpredictable climates with our integrated real-time weather forecasting widget, providing hyper-local data for your farm.',
        feature5Title: 'MULTILINGUAL SUPPORT',
        feature5Desc: 'Navigate the platform comfortably in your native tongue. AgriConnect seamlessly supports English, Telugu, Hindi, and Spanish.',
        feature6Title: 'EXPERT KNOWLEDGE BASE',
        feature6Desc: 'Explore an extensive library of articles, tutorials, and latest farming techniques published by certified agricultural scientists.',
        ctaHeadline: 'READY TO TRANSFORM YOUR AGRICULTURAL JOURNEY?',
        ctaButton: 'Sign In to AgriConnect',
        cropDiseaseDemo: 'Crop Disease Inspection For Free',
        statAccuracy: 'AI Disease Detection Accuracy',
        statClasses: 'Crop & Disease Classes Supported',
        statMarket: 'Real-Time Weather & Market Access',
        statExperts: 'Certified Agricultural Experts',
        roleAccessTitle: 'ROLE-BASED ACCESS TO ↓',
        roleAdmin: 'ADMIN',
        roleFarmer: 'FARMER',
        roleExpert: 'EXPERT',
        roleFinancier: 'FINANCIER',
        rolePublic: 'PUBLIC',
        save: 'Save',
        loading: 'Loading…',
        error: 'Error',
        success: 'Success',
        pending: 'Pending',
        resolved: 'Resolved',
        status: 'Status',
        author: 'Author',
        category: 'Category',
        description: 'Description',
        previous: 'Previous',
        next: 'Next',
        search: 'Search',

        // Farmer Home
        welcomefarmer: 'Welcome, Farmer!',
        farmerinspirationquote: 'The farmer is the only man in our economy who buys everything at retail, sells everything at wholesale, and pays the freight both ways.',
        quickactions: 'Quick Actions',

        // Crop Suggestion
        sendcropsuggestionrequest: 'Send Crop Suggestion Request',
        croptype: 'Crop Type',
        requestdetails: 'Request Details',
        district: 'District',
        state: 'State',
        location: 'Location',
        submitrequest: 'Submit Request',
        submitting: 'Submitting…',
        requestsubmittedsuccessfully: 'Request submitted successfully! We will reply shortly.',

        // Responses
        viewallresponses: 'View All Responses',
        allresponses: 'All Responses',
        expertemail: 'Expert Email',
        responsedetails: 'Response Details',
        noqueriesyet: 'No queries submitted yet.',
        awaitingresponse: 'Awaiting expert response…',
        yourquery: 'Your Query',
        expertresponse: 'Expert Response',

        // Loans
        viewallloans: 'View All Loans',
        searchloans: 'Search loans…',
        sortbyloantype: 'Sort by Loan Type',
        sortbyinterestrate: 'Sort by Interest Rate',
        sortbymaxamount: 'Sort by Max Amount',
        allloantypes: 'All Types',
        default: 'Default',
        lowtohigh: 'Low to High',
        hightolow: 'High to Low',
        loanid: 'Loan ID',
        interestrate: 'Interest Rate',
        maxamount: 'Maximum Amount',
        repaymentperiod: 'Repayment Period',
        months: 'months',
        applyforloan: 'Apply for Loan',
        noloansavailable: 'No loan products available yet.',
        croploan: 'Crop Loan',
        equipmentloan: 'Equipment Loan',
        soilimprovement: 'Soil Improvement',

        // Loan Application
        applicantname: 'Applicant Name',
        email: 'Email',
        contactnumber: 'Contact Number',
        uploaddocuments: 'Upload Documents',
        submitapplication: 'Submit Application',
        successfullyapplied: 'Application Submitted Successfully!',
        applyingforloantype: 'Applying for loan type',
        withinterestrate: 'with interest rate',
        maximumamountis: 'Maximum amount is',
        repaymentperiodis: 'Repayment period is',

        // Farming Content
        allfarmingcontent: 'All Farming Content',
        explorefarmingcontent: 'Explore Farming Content',
        showfull: 'Show Full',
        readmore: 'Read More',
        createddate: 'Created Date',
        noarticlesfound: 'No articles found.',

        // Sell Goods / Marketplace
        sellyourproduce: 'Sell Your Produce',
        addnewproduct: 'Add New Listing',
        myproducts: 'My Produce Listings',
        productname: 'Produce Name',
        selectcategory: 'Select Category',
        vegetables: 'Vegetables',
        fruits: 'Fruits',
        grains: 'Grains',
        dairy: 'Dairy',
        priceperkg: 'Price (₹ per unit)',
        availablequantity: 'Quantity',
        productimages: 'Product Images (optional)',
        harvestdate: 'Harvest Date (optional)',
        kg: 'kg',
        price: 'Price',
        quantity: 'Quantity',
        unit: 'Unit',
        createListing: 'Create Listing',
        creating: 'Creating…',
        remove: 'Remove',
        nolistingsyet: 'No listings yet. Add your produce above!',

        // Expert Section
        welcomeexpert: 'Welcome, Expert!',
        farmerrequests: 'Farmer Requests',
        myresponses: 'My Responses',
        allcontent: 'All Content',
        createarticle: 'Create Article',
        marketplacemanagement: 'Marketplace Management',
        geminiassistance: 'AgriBot AI',
        cropmap: 'Crop Suitability Map',
        pendingapproval: 'Pending Approval',
        activelistings: 'Active Listings',
        approve: 'Approve',
        reject: 'Reject',

        // Financier Section
        welcomefinancier: 'Welcome, Financier!',
        addloan: 'Add Loan',
        loanrequests: 'Loan Requests',
        allloans: 'All Loans',
        farmerloanportfolio: 'Farmer Loan Portfolio',
        accept: 'Accept',
        removeloan: 'Remove Loan',

        // Admin Section
        admindashboard: 'Admin Dashboard',
        managefarmers: 'Manage Farmers',
        manageexperts: 'Manage Experts',
        viewallsectors: 'View All Sectors',
        addfarmer: 'Add Farmer',
        addexpert: 'Add Expert',
        addfinancier: 'Add Financier',
        totalfarmers: 'Total Farmers',
        activeexperts: 'Active Experts',
        totalqueries: 'Total Queries',

        // Public User Section
        welcomeuser: 'Welcome, Explorer!',
        explorecontent: 'Explore Content',
        learnfarming: 'Learn Farming',
        buyresources: 'Buy Resources',
        contactfarmer: 'Contact Farmer',
        farmercontactrevealed: 'Farmer Contact Revealed',
    },

    hi: {
        // General
        welcome: 'स्वागत है',
        logout: 'लॉग आउट',
        login: 'लॉगिन',
        signin: 'साइन इन',
        register: 'रजिस्टर',
        home: 'होम',
        back: 'वापस',
        cancel: 'रद्द करें',
        edit: 'संपादित करें',
        delete: 'हटाएं',
        save: 'सहेजें',
        loading: 'लोड हो रहा है…',
        error: 'त्रुटि',
        success: 'सफलता',
        pending: 'लंबित',
        resolved: 'हल किया गया',
        status: 'स्थिति',
        author: 'लेखक',
        category: 'श्रेणी',
        description: 'विवरण',
        previous: 'पिछला',
        next: 'अगला',
        search: 'खोजें',

        // Landing Page
        newEra: 'खेती का नया युग',
        heroHeadline: 'किसानों को एक स्थायी भविष्य के लिए सशक्त बनाना',
        heroSubtext1: 'किसानों, विशेषज्ञों, फाइनेंसरों और उपभोक्ताओं के बीच की खाई को पाटना। सफलता विकसित करें',
        heroSubtext2: 'नवीनतम ज्ञान, नवाचार और समुदाय के माध्यम से लचीलापन।',
        getStarted: 'शुरू करें',
        joinAsFarmer: 'किसान के रूप में जुड़ें',
        exploreFeatures: 'विशेषताएं खोजें',
        feature1Title: 'फसल रोग का पता लगाना',
        feature1Desc: 'अपनी फसलों की तस्वीरें अपलोड करें। हमारा एआई-संचालित छवि विश्लेषण त्वरित निदान और उपचार प्रदान करता है, बाद में सत्यापित कृषि विशेषज्ञों द्वारा इसकी समीक्षा की जाती है।',
        feature2Title: 'प्रत्यक्ष बाज़ार',
        feature2Desc: 'बिचौलिए को दरकिनार करें। अधिकतम लाभ के लिए पारदर्शी, स्व-निर्धारित कीमतों पर अपनी उपज सीधे उपभोक्ताओं या व्यापारिक खरीदारों को बेचें।',
        feature3Title: 'आर्थिक सहायता',
        feature3Desc: 'पंजीकृत फाइनेंसरों से अनुरूप ऋण विकल्प और वित्तीय सहायता प्राप्त करें। सहजता से अनुरोध सबमिट करें और वास्तविक समय में स्वीकृतियों को ट्रैक करें।',
        feature4Title: 'रीयल-टाइम इनसाइट्स',
        feature4Desc: 'हमारे एकीकृत रीयल-टाइम मौसम पूर्वानुमान विजेट के साथ अप्रत्याशित जलवायु से आगे रहें, जो आपके खेत के लिए हाइपर-लोकल डेटा प्रदान करता है।',
        feature5Title: 'बहुभाषी सहायता',
        feature5Desc: 'मंच को अपनी मूल भाषा में आराम से नेविगेट करें। एग्रीकनेक्ट मूल रूप से अंग्रेजी, तेलुगु, हिंदी और स्पेनिश का समर्थन करता है।',
        feature6Title: 'विशेषज्ञ ज्ञानकोष',
        feature6Desc: 'प्रमाणित कृषि वैज्ञानिकों द्वारा प्रकाशित लेखों, ट्यूटोरियल और नवीनतम कृषि तकनीकों की एक विस्तृत लाइब्रेरी का अन्वेषण करें।',
        ctaHeadline: 'क्या आप अपनी कृषि यात्रा को बदलने के लिए तैयार हैं?',
        ctaButton: 'एग्रीकनेक्ट में साइन इन करें',
        cropDiseaseDemo: 'फसल रोग निरीक्षण मुफ्त में',
        statAccuracy: 'एआई रोग का पता लगाने की सटीकता',
        statClasses: 'फसल और रोग वर्ग समर्थित',
        statMarket: 'रीयल-टाइम मौसम और बाजार पहुंच',
        statExperts: 'प्रमाणित कृषि विशेषज्ञ',
        roleAccessTitle: 'भूमिका-आधारित पहुंच ↓',
        roleAdmin: 'व्यवस्थापक',
        roleFarmer: 'किसान',
        roleExpert: 'विशेषज्ञ',
        roleFinancier: 'वित्तपोषक',
        rolePublic: 'जनता',

        // Farmer Home
        welcomefarmer: 'स्वागत है, किसान!',
        farmerinspirationquote: 'किसान हमारी अर्थव्यवस्था का आधार है।',
        quickactions: 'त्वरित क्रियाएं',

        // Crop Suggestion
        sendcropsuggestionrequest: 'फसल सुझाव अनुरोध भेजें',
        croptype: 'फसल का प्रकार',
        requestdetails: 'अनुरोध विवरण',
        district: 'जिला',
        state: 'राज्य',
        location: 'स्थान',
        submitrequest: 'अनुरोध सबमिट करें',
        submitting: 'सबमिट हो रहा है…',
        requestsubmittedsuccessfully: 'अनुरोध सफलतापूर्वक सबमिट किया गया! हम जल्द जवाब देंगे।',

        // Responses
        viewallresponses: 'सभी उत्तर देखें',
        allresponses: 'सभी उत्तर',
        expertemail: 'विशेषज्ञ ईमेल',
        responsedetails: 'उत्तर विवरण',
        noqueriesyet: 'अभी तक कोई प्रश्न नहीं भेजा गया।',
        awaitingresponse: 'विशेषज्ञ उत्तर की प्रतीक्षा…',
        yourquery: 'आपका प्रश्न',
        expertresponse: 'विशेषज्ञ का उत्तर',

        // Loans
        viewallloans: 'सभी ऋण देखें',
        searchloans: 'ऋण खोजें…',
        sortbyloantype: 'ऋण प्रकार से क्रमबद्ध करें',
        sortbyinterestrate: 'ब्याज दर से क्रमबद्ध करें',
        sortbymaxamount: 'अधिकतम राशि से क्रमबद्ध करें',
        allloantypes: 'सभी प्रकार',
        default: 'डिफ़ॉल्ट',
        lowtohigh: 'कम से अधिक',
        hightolow: 'अधिक से कम',
        loanid: 'ऋण आईडी',
        interestrate: 'ब्याज दर',
        maxamount: 'अधिकतम राशि',
        repaymentperiod: 'पुनर्भुगतान अवधि',
        months: 'महीने',
        applyforloan: 'ऋण के लिए आवेदन करें',
        noloansavailable: 'अभी कोई ऋण उत्पाद उपलब्ध नहीं है।',
        croploan: 'फसल ऋण',
        equipmentloan: 'उपकरण ऋण',
        soilimprovement: 'मिट्टी सुधार',

        // Loan Application
        applicantname: 'आवेदक का नाम',
        email: 'ईमेल',
        contactnumber: 'संपर्क नंबर',
        uploaddocuments: 'दस्तावेज़ अपलोड करें',
        submitapplication: 'आवेदन सबमिट करें',
        successfullyapplied: 'आवेदन सफलतापूर्वक सबमिट हुआ!',
        applyingforloantype: 'ऋण प्रकार के लिए आवेदन कर रहे हैं',
        withinterestrate: 'ब्याज दर के साथ',
        maximumamountis: 'अधिकतम राशि है',
        repaymentperiodis: 'पुनर्भुगतान अवधि है',

        // Farming Content
        allfarmingcontent: 'सभी कृषि सामग्री',
        explorefarmingcontent: 'कृषि सामग्री देखें',
        showfull: 'पूरा देखें',
        readmore: 'और पढ़ें',
        createddate: 'बनाने की तारीख',
        noarticlesfound: 'कोई लेख नहीं मिला।',

        // Sell Goods
        sellyourproduce: 'अपनी उपज बेचें',
        addnewproduct: 'नई सूची जोड़ें',
        myproducts: 'मेरी उपज सूचियां',
        productname: 'उपज का नाम',
        selectcategory: 'श्रेणी चुनें',
        vegetables: 'सब्जियां',
        fruits: 'फल',
        grains: 'अनाज',
        dairy: 'डेयरी',
        priceperkg: 'मूल्य (₹ प्रति इकाई)',
        availablequantity: 'मात्रा',
        productimages: 'उत्पाद छवियां (वैकल्पिक)',
        harvestdate: 'कटाई की तारीख (वैकल्पिक)',
        kg: 'किग्रा',
        price: 'मूल्य',
        quantity: 'मात्रा',
        unit: 'इकाई',
        createListing: 'सूची बनाएं',
        creating: 'बनाया जा रहा है…',
        remove: 'हटाएं',
        nolistingsyet: 'अभी कोई सूची नहीं। ऊपर अपनी उपज जोड़ें!',

        // Expert
        welcomeexpert: 'स्वागत है, विशेषज्ञ!',
        farmerrequests: 'किसान अनुरोध',
        myresponses: 'मेरे उत्तर',
        allcontent: 'सभी सामग्री',
        createarticle: 'लेख बनाएं',
        marketplacemanagement: 'बाज़ार प्रबंधन',
        geminiassistance: 'AgriBot AI',
        cropmap: 'फसल उपयुक्तता नक्शा',
        pendingapproval: 'अनुमोदन लंबित',
        activelistings: 'सक्रिय सूचियां',
        approve: 'स्वीकृत करें',
        reject: 'अस्वीकार करें',

        // Financier
        welcomefinancier: 'स्वागत है, वित्तपोषक!',
        addloan: 'ऋण जोड़ें',
        loanrequests: 'ऋण अनुरोध',
        allloans: 'सभी ऋण',
        farmerloanportfolio: 'किसान ऋण पोर्टफोलियो',
        accept: 'स्वीकार करें',
        removeloan: 'ऋण हटाएं',

        // Admin
        admindashboard: 'व्यवस्थापक डैशबोर्ड',
        managefarmers: 'किसान प्रबंधन',
        manageexperts: 'विशेषज्ञ प्रबंधन',
        viewallsectors: 'सभी क्षेत्र देखें',
        addfarmer: 'किसान जोड़ें',
        addexpert: 'विशेषज्ञ जोड़ें',
        addfinancier: 'वित्तपोषक जोड़ें',
        totalfarmers: 'कुल किसान',
        activeexperts: 'सक्रिय विशेषज्ञ',
        totalqueries: 'कुल प्रश्न',

        // Public
        welcomeuser: 'स्वागत है, अन्वेषक!',
        explorecontent: 'सामग्री देखें',
        learnfarming: 'खेती सीखें',
        buyresources: 'संसाधन खरीदें',
        contactfarmer: 'किसान से संपर्क',
        farmercontactrevealed: 'किसान संपर्क प्रकट',
    },

    te: {
        // General
        welcome: 'స్వాగతం',
        logout: 'లాగ్ అవుట్',
        login: 'లాగిన్',
        signin: 'సైన్ ఇన్',
        register: 'నమోదు చేయండి',
        home: 'హోమ్',
        back: 'వెనక్కి',
        cancel: 'రద్దు',
        edit: 'సవరించు',
        delete: 'తొలగించు',
        save: 'సేవ్ చేయి',
        loading: 'లోడవుతోంది…',
        error: 'లోపం',
        success: 'విజయం',
        pending: 'పెండింగ్',
        resolved: 'పరిష్కరించబడింది',
        status: 'స్థితి',
        author: 'రచయిత',
        category: 'వర్గం',
        description: 'వివరణ',
        previous: 'మునుపటి',
        next: 'తదుపరి',
        search: 'వెతుకు',

        // Landing Page
        newEra: 'వ్యవసాయంలో కొత్త శకం',
        heroHeadline: 'సుస్థిర భవిష్యత్తు కోసం రైతులను సన్నద్ధం చేయడం',
        heroSubtext1: 'రైతులు, నిపుణులు, ఫైనాన్షియర్లు మరియు వినియోగదారుల మధ్య అంతరాన్ని తగ్గించడం. విజయాన్ని పండించండి',
        heroSubtext2: 'అధునాతన జ్ఞానం, ఆవిష్కరణ మరియు సంఘం ద్వారా స్థితిస్థాపకత.',
        getStarted: 'ప్రారంభించండి',
        joinAsFarmer: 'రైతుగా చేరండి',
        exploreFeatures: 'లక్షణాలను అన్వేషించండి',
        feature1Title: 'పంట వ్యాధి గుర్తింపు',
        feature1Desc: 'మీ పంటల ఫోటోలను అప్‌లోడ్ చేయండి. మా AI-ఆధారిత ఇమేజ్ విశ్లేషణ తక్షణ రోగనిర్ధారణ మరియు నివారణలను అందిస్తుంది, తరువాత ధృవీకరించబడిన వ్యవసాయ నిపుణులచే సమీక్షించబడుతుంది.',
        feature2Title: 'ప్రత్యక్ష మార్కెట్‌ప్లేస్',
        feature2Desc: 'మధ్యవర్తులను దాటవేయండి. గరిష్ట లాభం కోసం పారదర్శక, స్వీయ-నిర్ణీత ధరలకు వినియోగదారులు లేదా వ్యాపార కొనుగోలుదారులకు నేరుగా మీ ఉత్పత్తులను విక్రయించండి.',
        feature3Title: 'ఆర్థిక సహాయం',
        feature3Desc: 'నమోదిత ఫైనాన్షియర్‌ల నుండి అనుకూలీకరించిన రుణ ఎంపికలు మరియు ఆర్థిక సహాయాన్ని యాక్సెస్ చేయండి. అప్రయత్నంగా అభ్యర్థనలను సమర్పించండి మరియు నిజ సమయంలో ఆమోదాలను ట్రాక్ చేయండి.',
        feature4Title: 'రియల్-టైమ్ అంతర్దృష్టులు',
        feature4Desc: 'మా ఇంటిగ్రేటెడ్ రియల్-టైమ్ వాతావరణ అంచనా విడ్జెట్‌తో అనూహ్య వాతావరణాల కంటే ముందుండండి, మీ పొలానికి హైపర్-లోకల్ డేటాను అందిస్తుంది.',
        feature5Title: 'బహుభాషా మద్దతు',
        feature5Desc: 'మీ మాతృభాషలో ప్లాట్‌ఫారమ్‌ను సౌకర్యవంతంగా నావిగేట్ చేయండి. అగ్రి కనెక్ట్ ఇంగ్లీష్, తెలుగు, హిందీ మరియు స్పానిష్ భాషలకు మద్దతు ఇస్తుంది.',
        feature6Title: 'నిపుణుల నాలెడ్జ్ బేస్',
        feature6Desc: 'ధృవీకరించబడిన వ్యవసాయ శాస్త్రవేత్తలు ప్రచురించిన కథనాలు, ట్యుటోరియల్స్ మరియు తాజా వ్యవసాయ సాంకేతికతలతో కూడిన విస్తృతమైన లైబ్రరీని అన్వేషించండి.',
        ctaHeadline: 'మీ వ్యవసాయ ప్రయాణాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?',
        ctaButton: 'అగ్రి కనెక్ట్‌కి సైన్ ఇన్ చేయండి',
        cropDiseaseDemo: 'పంట వ్యాధి తనిఖీ ఉచితంగా',
        statAccuracy: 'AI వ్యాధి గుర్తింపు ఖచ్చితత్వం',
        statClasses: 'మద్దతు ఉన్న పంట మరియు వ్యాధి తరగతులు',
        statMarket: 'రియల్-టైమ్ వాతావరణం మరియు మార్కెట్ యాక్సెస్',
        statExperts: 'ధృవీకరించబడిన వ్యవసాయ నిపుణులు',
        roleAccessTitle: 'పాత్ర ఆధారిత యాక్సెస్ ↓',
        roleAdmin: 'అడ్మిన్',
        roleFarmer: 'రైతు',
        roleExpert: 'నిపుణుడు',
        roleFinancier: 'ఫైనాన్షియర్',
        rolePublic: 'ప్రజా',

        // Farmer Home
        welcomefarmer: 'స్వాగతం, రైతు!',
        farmerinspirationquote: 'రైతు మన దేశానికి వెన్నెముక.',
        quickactions: 'శీఘ్ర చర్యలు',

        // Crop Suggestion
        sendcropsuggestionrequest: 'పంట సూచన అభ్యర్థన పంపండి',
        croptype: 'పంట రకం',
        requestdetails: 'అభ్యర్థన వివరాలు',
        district: 'జిల్లా',
        state: 'రాష్ట్రం',
        location: 'స్థానం',
        submitrequest: 'అభ్యర్థన సమర్పించండి',
        submitting: 'సమర్పిస్తోంది…',
        requestsubmittedsuccessfully: 'అభ్యర్థన విజయంగా సమర్పించబడింది! మేము త్వరలో జవాబిస్తాం.',

        // Responses
        viewallresponses: 'అన్ని స్పందనలు చూడండి',
        allresponses: 'అన్ని స్పందనలు',
        expertemail: 'నిపుణుని ఇమెయిల్',
        responsedetails: 'స్పందన వివరాలు',
        noqueriesyet: 'ఇంకా ఏ ప్రశ్నా సమర్పించబడలేదు.',
        awaitingresponse: 'నిపుణుని స్పందన కోసం వేచి ఉంది…',
        yourquery: 'మీ ప్రశ్న',
        expertresponse: 'నిపుణుని స్పందన',

        // Loans
        viewallloans: 'అన్ని రుణాలు చూడండి',
        searchloans: 'రుణాలు వెతుకు…',
        sortbyloantype: 'రుణ రకం ద్వారా క్రమబద్ధీకరించు',
        sortbyinterestrate: 'వడ్డీ రేటు ద్వారా క్రమబద్ధీకరించు',
        sortbymaxamount: 'గరిష్ట మొత్తం ద్వారా క్రమబద్ధీకరించు',
        allloantypes: 'అన్ని రకాలు',
        default: 'డిఫాల్ట్',
        lowtohigh: 'తక్కువ నుండి ఎక్కువ',
        hightolow: 'ఎక్కువ నుండి తక్కువ',
        loanid: 'రుణ ID',
        interestrate: 'వడ్డీ రేటు',
        maxamount: 'గరిష్ట మొత్తం',
        repaymentperiod: 'తిరిగి చెల్లింపు వ్యవధి',
        months: 'నెలలు',
        applyforloan: 'రుణానికి దరఖాస్తు చేయండి',
        noloansavailable: 'ఇంకా రుణ ఉత్పత్తులు అందుబాటులో లేవు.',
        croploan: 'పంట రుణం',
        equipmentloan: 'పరికరాల రుణం',
        soilimprovement: 'నేల మెరుగుదల',

        // Loan Application
        applicantname: 'దరఖాస్తుదారు పేరు',
        email: 'ఇమెయిల్',
        contactnumber: 'సంప్రదింపు నంబర్',
        uploaddocuments: 'పత్రాలు అప్‌లోడ్ చేయండి',
        submitapplication: 'దరఖాస్తు సమర్పించండి',
        successfullyapplied: 'దరఖాస్తు విజయంగా సమర్పించబడింది!',
        applyingforloantype: 'రుణ రకానికి దరఖాస్తు చేస్తున్నావు',
        withinterestrate: 'వడ్డీ రేటుతో',
        maximumamountis: 'గరిష్ట మొత్తం',
        repaymentperiodis: 'తిరిగి చెల్లింపు వ్యవధి',

        // Farming Content
        allfarmingcontent: 'అన్ని వ్యవసాయ కంటెంట్',
        explorefarmingcontent: 'వ్యవసాయ కంటెంట్ అన్వేషించు',
        showfull: 'పూర్తిగా చూడు',
        readmore: 'మరింత చదవండి',
        createddate: 'సృష్టించిన తేదీ',
        noarticlesfound: 'వ్యాసాలు కనుగొనబడలేదు.',

        // Sell Goods
        sellyourproduce: 'మీ ఉత్పత్తి అమ్మండి',
        addnewproduct: 'కొత్త జాబితా జోడించు',
        myproducts: 'నా ఉత్పత్తి జాబితాలు',
        productname: 'ఉత్పత్తి పేరు',
        selectcategory: 'వర్గాన్ని ఎంచుకోండి',
        vegetables: 'కూరగాయలు',
        fruits: 'పండ్లు',
        grains: 'ధాన్యాలు',
        dairy: 'డైరీ',
        priceperkg: 'ధర (₹ ప్రతి యూనిట్)',
        availablequantity: 'పరిమాణం',
        productimages: 'ఉత్పత్తి చిత్రాలు (ఐచ్ఛికం)',
        harvestdate: 'పంట తేదీ (ఐచ్ఛికం)',
        kg: 'కిలో',
        price: 'ధర',
        quantity: 'పరిమాణం',
        unit: 'యూనిట్',
        createListing: 'జాబితా సృష్టించు',
        creating: 'సృష్టిస్తోంది…',
        remove: 'తొలగించు',
        nolistingsyet: 'ఇంకా జాబితాలు లేవు. పైన మీ ఉత్పత్తి జోడించండి!',

        // Expert
        welcomeexpert: 'స్వాగతం, నిపుణుడా!',
        farmerrequests: 'రైతు అభ్యర్థనలు',
        myresponses: 'నా స్పందనలు',
        allcontent: 'మొత్తం కంటెంట్',
        createarticle: 'వ్యాసం సృష్టించు',
        marketplacemanagement: 'మార్కెట్ నిర్వహణ',
        geminiassistance: 'AgriBot AI',
        cropmap: 'పంట అనుకూలత మ్యాప్',
        pendingapproval: 'ఆమోదం పెండింగ్‌లో ఉంది',
        activelistings: 'యాక్టివ్ జాబితాలు',
        approve: 'ఆమోదించు',
        reject: 'తిరస్కరించు',

        // Financier
        welcomefinancier: 'స్వాగతం, ఫైనాన్సియర్!',
        addloan: 'రుణం జోడించు',
        loanrequests: 'రుణ అభ్యర్థనలు',
        allloans: 'అన్ని రుణాలు',
        farmerloanportfolio: 'రైతు రుణ పోర్ట్‌ఫోలియో',
        accept: 'అంగీకరించు',
        removeloan: 'రుణం తొలగించు',

        // Admin
        admindashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
        managefarmers: 'రైతులను నిర్వహించు',
        manageexperts: 'నిపుణులను నిర్వహించు',
        viewallsectors: 'అన్ని రంగాలు చూడు',
        addfarmer: 'రైతును జోడించు',
        addexpert: 'నిపుణుడిని జోడించు',
        addfinancier: 'ఫైనాన్సియర్‌ని జోడించు',
        totalfarmers: 'మొత్తం రైతులు',
        activeexperts: 'యాక్టివ్ నిపుణులు',
        totalqueries: 'మొత్తం ప్రశ్నలు',

        // Public
        welcomeuser: 'స్వాగతం, అన్వేషకుడా!',
        explorecontent: 'కంటెంట్ అన్వేషించు',
        learnfarming: 'వ్యవసాయం నేర్చుకో',
        buyresources: 'వనరులు కొనుగోలు',
        contactfarmer: 'రైతును సంప్రదించు',
        farmercontactrevealed: 'రైతు సంప్రదింపు వెల్లడైంది',
    },

    fr: {
        // General
        welcome: 'Bienvenue',
        logout: 'Déconnexion',
        login: 'Connexion',
        signin: 'Se connecter',
        register: 'S\'inscrire',
        home: 'Accueil',
        back: 'Retour',
        cancel: 'Annuler',
        edit: 'Modifier',
        delete: 'Supprimer',
        save: 'Enregistrer',
        loading: 'Chargement…',
        error: 'Erreur',
        success: 'Succès',
        pending: 'En attente',
        resolved: 'Résolu',
        status: 'Statut',
        author: 'Auteur',
        category: 'Catégorie',
        description: 'Description',
        previous: 'Précédent',
        next: 'Suivant',
        search: 'Recherche',

        // Landing Page
        newEra: 'UNE NOUVELLE ÈRE DE L\'AGRICULTURE',
        heroHeadline: 'DONNER AUX AGRICULTEURS LES MOYENS D\'UN AVENIR DURABLE',
        heroSubtext1: 'Combler le fossé entre les agriculteurs, les experts, les financiers et les consommateurs. Cultivez le succès',
        heroSubtext2: 'et la résilience grâce aux connaissances de pointe, à l\'innovation et à la communauté.',
        getStarted: 'Commencer',
        joinAsFarmer: 'Rejoindre en tant qu\'agriculteur',
        exploreFeatures: 'EXPLORER LES FONCTIONNALITÉS',
        feature1Title: 'DÉTECTION DES MALADIES DES CULTURES',
        feature1Desc: 'Téléchargez des photos de vos cultures. Notre analyse d\'images par IA fournit des diagnostics et des remèdes instantanés, examinés ensuite par des experts agricoles vérifiés.',
        feature2Title: 'MARCHÉ DIRECT',
        feature2Desc: 'Contournez les intermédiaires. Vendez vos produits directement aux consommateurs ou aux acheteurs professionnels à des prix transparents et auto-attribués pour une rentabilité maximale.',
        feature3Title: 'SOUTIEN FINANCIER',
        feature3Desc: 'Accédez à des options de prêt sur mesure et à une aide financière de la part de financiers enregistrés. Soumettez des demandes sans effort et suivez les approbations en temps réel.',
        feature4Title: 'INFORMATIONS EN TEMPS RÉEL',
        feature4Desc: 'Gardez une longueur d\'avance sur les climats imprévisibles grâce à notre widget de prévisions météorologiques en temps réel intégré, fournissant des données hyper-locales pour votre ferme.',
        feature5Title: 'SUPPORT MULTILINGUE',
        feature5Desc: 'Naviguez confortablement sur la plateforme dans votre langue maternelle. AgriConnect prend en charge de manière transparente l\'anglais, le telugu, le hindi et le français.',
        feature6Title: 'BASE DE CONNAISSANCES D\'EXPERTS',
        feature6Desc: 'Explorez une vaste bibliothèque d\'articles, de tutoriels et les dernières techniques agricoles publiées par des scientifiques agricoles certifiés.',
        ctaHeadline: 'PRÊT À TRANSFORMER VOTRE PARCOURS AGRICOLE ?',
        ctaButton: 'Se connecter à AgriConnect',
        cropDiseaseDemo: 'Inspection des maladies des cultures gratuitement',
        statAccuracy: 'Précision de détection des maladies de l\'IA',
        statClasses: 'Classes de cultures et de maladies prises en charge',
        statMarket: 'Accès en temps réel à la météo et au marché',
        statExperts: 'Experts agricoles certifiés',
        roleAccessTitle: 'ACCÈS BASÉ SUR LES RÔLES ↓',
        roleAdmin: 'ADMIN',
        roleFarmer: 'AGRICULTEUR',
        roleExpert: 'EXPERT',
        roleFinancier: 'FINANCIER',
        rolePublic: 'PUBLIC',

        // Farmer Home
        welcomefarmer: 'Bienvenue, Agriculteur !',
        farmerinspirationquote: 'L\'agriculteur est la colonne vertébrale de notre économie.',
        quickactions: 'Actions Rapides',

        // Crop Suggestion
        sendcropsuggestionrequest: 'Envoyer une demande de suggestion de culture',
        croptype: 'Type de culture',
        requestdetails: 'Détails de la demande',
        district: 'District',
        state: 'État',
        location: 'Emplacement',
        submitrequest: 'Soumettre la demande',
        submitting: 'Soumission…',
        requestsubmittedsuccessfully: 'Demande soumise avec succès ! Nous répondrons sous peu.',

        // Responses
        viewallresponses: 'Voir toutes les réponses',
        allresponses: 'Toutes les réponses',
        expertemail: 'E-mail de l\'expert',
        responsedetails: 'Détails de la réponse',
        noqueriesyet: 'Aucune requête soumise pour le moment.',
        awaitingresponse: 'En attente de la réponse de l\'expert…',
        yourquery: 'Votre requête',
        expertresponse: 'Réponse de l\'expert',

        // Loans
        viewallloans: 'Voir tous les prêts',
        searchloans: 'Rechercher des prêts…',
        sortbyloantype: 'Trier par type de prêt',
        sortbyinterestrate: 'Trier par taux d\'intérêt',
        sortbymaxamount: 'Trier par montant maximum',
        allloantypes: 'Tous les types',
        default: 'Défaut',
        lowtohigh: 'Croissant',
        hightolow: 'Décroissant',
        loanid: 'ID du prêt',
        interestrate: 'Taux d\'intérêt',
        maxamount: 'Montant maximal',
        repaymentperiod: 'Période de remboursement',
        months: 'mois',
        applyforloan: 'Demander un prêt',
        noloansavailable: 'Aucun produit de prêt disponible pour le moment.',
        croploan: 'Prêt agricole',
        equipmentloan: 'Prêt d\'équipement',
        soilimprovement: 'Amélioration des sols',

        // Loan Application
        applicantname: 'Nom du demandeur',
        email: 'E-mail',
        contactnumber: 'Numéro de contact',
        uploaddocuments: 'Télécharger des documents',
        submitapplication: 'Soumettre la demande',
        successfullyapplied: 'Demande soumise avec succès !',
        applyingforloantype: 'Demande pour le type de prêt',
        withinterestrate: 'avec taux d\'intérêt',
        maximumamountis: 'Le montant maximum est',
        repaymentperiodis: 'La période de remboursement est',

        // Farming Content
        allfarmingcontent: 'Tout le contenu agricole',
        explorefarmingcontent: 'Explorer le contenu agricole',
        showfull: 'Afficher tout',
        readmore: 'Lire la suite',
        createddate: 'Date de création',
        noarticlesfound: 'Aucun article trouvé.',

        // Sell Goods
        sellyourproduce: 'Vendez vos produits',
        addnewproduct: 'Ajouter une nouvelle annonce',
        myproducts: 'Mes annonces',
        productname: 'Nom du produit',
        selectcategory: 'Sélectionner la catégorie',
        vegetables: 'Légumes',
        fruits: 'Fruits',
        grains: 'Céréales',
        dairy: 'Produits laitiers',
        priceperkg: 'Prix (₹ par unité)',
        availablequantity: 'Quantité',
        productimages: 'Images du produit (facultatif)',
        harvestdate: 'Date de récolte (facultatif)',
        kg: 'kg',
        price: 'Prix',
        quantity: 'Quantité',
        unit: 'Unité',
        createListing: 'Créer l\'annonce',
        creating: 'Création…',
        remove: 'Supprimer',
        nolistingsyet: 'Aucune annonce pour le moment. Ajoutez vos produits ci-dessus !',

        // Expert
        welcomeexpert: 'Bienvenue, Expert !',
        farmerrequests: 'Demandes des agriculteurs',
        myresponses: 'Mes réponses',
        allcontent: 'Tout le contenu',
        createarticle: 'Créer un article',
        marketplacemanagement: 'Gestion du marché',
        geminiassistance: 'AgriBot AI',
        cropmap: 'Carte des cultures',
        pendingapproval: 'En attente d\'approbation',
        activelistings: 'Annonces actives',
        approve: 'Approuver',
        reject: 'Rejeter',

        // Financier
        welcomefinancier: 'Bienvenue, Financier !',
        addloan: 'Ajouter un prêt',
        loanrequests: 'Demandes de prêt',
        allloans: 'Tous les prêts',
        farmerloanportfolio: 'Portefeuille de prêts',
        accept: 'Accepter',
        removeloan: 'Supprimer le prêt',

        // Admin
        admindashboard: 'Tableau de bord de l\'administrateur',
        managefarmers: 'Gérer les agriculteurs',
        manageexperts: 'Gérer les experts',
        viewallsectors: 'Voir tous les secteurs',
        addfarmer: 'Ajouter un agriculteur',
        addexpert: 'Ajouter un expert',
        addfinancier: 'Ajouter un financier',
        totalfarmers: 'Total des agriculteurs',
        activeexperts: 'Experts actifs',
        totalqueries: 'Total des requêtes',

        // Public
        welcomeuser: 'Bienvenue, Explorateur !',
        explorecontent: 'Explorer le contenu',
        learnfarming: 'Apprendre l\'agriculture',
        buyresources: 'Acheter des ressources',
        contactfarmer: 'Contacter l\'agriculteur',
        farmercontactrevealed: 'Contact de l\'agriculteur révélé',
    },
}

export const t = (key, language = 'en') => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key
}

export default t
