/**
 * translate.js — Full translation lookup helper
 * Languages: English (en), Hindi (hi), Telugu (te), Spanish (es)
 */
const TRANSLATIONS = {
    en: {
        // General
        welcome: 'Welcome',
        logout: 'Logout',
        login: 'Login',
        home: 'Home',
        back: 'Back',
        cancel: 'Cancel',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        loading: 'Loading…',
        error: 'Error',
        success: 'Success',
        pending: 'Pending',
        resolved: 'Resolved',
        status: 'Status',
        author: 'Author',
        category: 'Category',
        description: 'Description',
        previous: 'Previous',
        next: 'Next',
        search: 'Search',

        // Farmer Home
        welcomefarmer: 'Welcome, Farmer!',
        farmerinspirationquote: 'The farmer is the only man in our economy who buys everything at retail, sells everything at wholesale, and pays the freight both ways.',
        quickactions: 'Quick Actions',

        // Crop Suggestion
        sendcropsuggestionrequest: 'Send Crop Suggestion Request',
        croptype: 'Crop Type',
        requestdetails: 'Request Details',
        district: 'District',
        state: 'State',
        location: 'Location',
        submitrequest: 'Submit Request',
        submitting: 'Submitting…',
        requestsubmittedsuccessfully: 'Request submitted successfully! We will reply shortly.',

        // Responses
        viewallresponses: 'View All Responses',
        allresponses: 'All Responses',
        expertemail: 'Expert Email',
        responsedetails: 'Response Details',
        noqueriesyet: 'No queries submitted yet.',
        awaitingresponse: 'Awaiting expert response…',
        yourquery: 'Your Query',
        expertresponse: 'Expert Response',

        // Loans
        viewallloans: 'View All Loans',
        searchloans: 'Search loans…',
        sortbyloantype: 'Sort by Loan Type',
        sortbyinterestrate: 'Sort by Interest Rate',
        sortbymaxamount: 'Sort by Max Amount',
        allloantypes: 'All Types',
        default: 'Default',
        lowtohigh: 'Low to High',
        hightolow: 'High to Low',
        loanid: 'Loan ID',
        interestrate: 'Interest Rate',
        maxamount: 'Maximum Amount',
        repaymentperiod: 'Repayment Period',
        months: 'months',
        applyforloan: 'Apply for Loan',
        noloansavailable: 'No loan products available yet.',
        croploan: 'Crop Loan',
        equipmentloan: 'Equipment Loan',
        soilimprovement: 'Soil Improvement',

        // Loan Application
        applicantname: 'Applicant Name',
        email: 'Email',
        contactnumber: 'Contact Number',
        uploaddocuments: 'Upload Documents',
        submitapplication: 'Submit Application',
        successfullyapplied: 'Application Submitted Successfully!',
        applyingforloantype: 'Applying for loan type',
        withinterestrate: 'with interest rate',
        maximumamountis: 'Maximum amount is',
        repaymentperiodis: 'Repayment period is',

        // Farming Content
        allfarmingcontent: 'All Farming Content',
        explorefarmingcontent: 'Explore Farming Content',
        showfull: 'Show Full',
        readmore: 'Read More',
        createddate: 'Created Date',
        noarticlesfound: 'No articles found.',

        // Sell Goods / Marketplace
        sellyourproduce: 'Sell Your Produce',
        addnewproduct: 'Add New Listing',
        myproducts: 'My Produce Listings',
        productname: 'Produce Name',
        selectcategory: 'Select Category',
        vegetables: 'Vegetables',
        fruits: 'Fruits',
        grains: 'Grains',
        dairy: 'Dairy',
        priceperkg: 'Price (₹ per unit)',
        availablequantity: 'Quantity',
        productimages: 'Product Images (optional)',
        harvestdate: 'Harvest Date (optional)',
        kg: 'kg',
        price: 'Price',
        quantity: 'Quantity',
        unit: 'Unit',
        createListing: 'Create Listing',
        creating: 'Creating…',
        remove: 'Remove',
        nolistingsyet: 'No listings yet. Add your produce above!',
    },

    hi: {
        // General
        welcome: 'स्वागत है',
        logout: 'लॉग आउट',
        login: 'लॉगिन',
        home: 'होम',
        back: 'वापस',
        cancel: 'रद्द करें',
        edit: 'संपादित करें',
        delete: 'हटाएं',
        save: 'सहेजें',
        loading: 'लोड हो रहा है…',
        error: 'त्रुटि',
        success: 'सफलता',
        pending: 'लंबित',
        resolved: 'हल किया गया',
        status: 'स्थिति',
        author: 'लेखक',
        category: 'श्रेणी',
        description: 'विवरण',
        previous: 'पिछला',
        next: 'अगला',
        search: 'खोजें',

        // Farmer Home
        welcomefarmer: 'स्वागत है, किसान!',
        farmerinspirationquote: 'किसान हमारी अर्थव्यवस्था का आधार है।',
        quickactions: 'त्वरित क्रियाएं',

        // Crop Suggestion
        sendcropsuggestionrequest: 'फसल सुझाव अनुरोध भेजें',
        croptype: 'फसल का प्रकार',
        requestdetails: 'अनुरोध विवरण',
        district: 'जिला',
        state: 'राज्य',
        location: 'स्थान',
        submitrequest: 'अनुरोध सबमिट करें',
        submitting: 'सबमिट हो रहा है…',
        requestsubmittedsuccessfully: 'अनुरोध सफलतापूर्वक सबमिट किया गया! हम जल्द जवाब देंगे।',

        // Responses
        viewallresponses: 'सभी उत्तर देखें',
        allresponses: 'सभी उत्तर',
        expertemail: 'विशेषज्ञ ईमेल',
        responsedetails: 'उत्तर विवरण',
        noqueriesyet: 'अभी तक कोई प्रश्न नहीं भेजा गया।',
        awaitingresponse: 'विशेषज्ञ उत्तर की प्रतीक्षा…',
        yourquery: 'आपका प्रश्न',
        expertresponse: 'विशेषज्ञ का उत्तर',

        // Loans
        viewallloans: 'सभी ऋण देखें',
        searchloans: 'ऋण खोजें…',
        sortbyloantype: 'ऋण प्रकार से क्रमबद्ध करें',
        sortbyinterestrate: 'ब्याज दर से क्रमबद्ध करें',
        sortbymaxamount: 'अधिकतम राशि से क्रमबद्ध करें',
        allloantypes: 'सभी प्रकार',
        default: 'डिफ़ॉल्ट',
        lowtohigh: 'कम से अधिक',
        hightolow: 'अधिक से कम',
        loanid: 'ऋण आईडी',
        interestrate: 'ब्याज दर',
        maxamount: 'अधिकतम राशि',
        repaymentperiod: 'पुनर्भुगतान अवधि',
        months: 'महीने',
        applyforloan: 'ऋण के लिए आवेदन करें',
        noloansavailable: 'अभी कोई ऋण उत्पाद उपलब्ध नहीं है।',
        croploan: 'फसल ऋण',
        equipmentloan: 'उपकरण ऋण',
        soilimprovement: 'मिट्टी सुधार',

        // Loan Application
        applicantname: 'आवेदक का नाम',
        email: 'ईमेल',
        contactnumber: 'संपर्क नंबर',
        uploaddocuments: 'दस्तावेज़ अपलोड करें',
        submitapplication: 'आवेदन सबमिट करें',
        successfullyapplied: 'आवेदन सफलतापूर्वक सबमिट हुआ!',
        applyingforloantype: 'ऋण प्रकार के लिए आवेदन कर रहे हैं',
        withinterestrate: 'ब्याज दर के साथ',
        maximumamountis: 'अधिकतम राशि है',
        repaymentperiodis: 'पुनर्भुगतान अवधि है',

        // Farming Content
        allfarmingcontent: 'सभी कृषि सामग्री',
        explorefarmingcontent: 'कृषि सामग्री देखें',
        showfull: 'पूरा देखें',
        readmore: 'और पढ़ें',
        createddate: 'बनाने की तारीख',
        noarticlesfound: 'कोई लेख नहीं मिला।',

        // Sell Goods
        sellyourproduce: 'अपनी उपज बेचें',
        addnewproduct: 'नई सूची जोड़ें',
        myproducts: 'मेरी उपज सूचियां',
        productname: 'उपज का नाम',
        selectcategory: 'श्रेणी चुनें',
        vegetables: 'सब्जियां',
        fruits: 'फल',
        grains: 'अनाज',
        dairy: 'डेयरी',
        priceperkg: 'मूल्य (₹ प्रति इकाई)',
        availablequantity: 'मात्रा',
        productimages: 'उत्पाद छवियां (वैकल्पिक)',
        harvestdate: 'कटाई की तारीख (वैकल्पिक)',
        kg: 'किग्रा',
        price: 'मूल्य',
        quantity: 'मात्रा',
        unit: 'इकाई',
        createListing: 'सूची बनाएं',
        creating: 'बनाया जा रहा है…',
        remove: 'हटाएं',
        nolistingsyet: 'अभी कोई सूची नहीं। ऊपर अपनी उपज जोड़ें!',
    },

    te: {
        // General
        welcome: 'స్వాగతం',
        logout: 'లాగ్ అవుట్',
        login: 'లాగిన్',
        home: 'హోమ్',
        back: 'వెనక్కి',
        cancel: 'రద్దు',
        edit: 'సవరించు',
        delete: 'తొలగించు',
        save: 'సేవ్ చేయి',
        loading: 'లోడవుతోంది…',
        error: 'లోపం',
        success: 'విజయం',
        pending: 'పెండింగ్',
        resolved: 'పరిష్కరించబడింది',
        status: 'స్థితి',
        author: 'రచయిత',
        category: 'వర్గం',
        description: 'వివరణ',
        previous: 'మునుపటి',
        next: 'తదుపరి',
        search: 'వెతుకు',

        // Farmer Home
        welcomefarmer: 'స్వాగతం, రైతు!',
        farmerinspirationquote: 'రైతు మన దేశానికి వెన్నెముక.',
        quickactions: 'శీఘ్ర చర్యలు',

        // Crop Suggestion
        sendcropsuggestionrequest: 'పంట సూచన అభ్యర్థన పంపండి',
        croptype: 'పంట రకం',
        requestdetails: 'అభ్యర్థన వివరాలు',
        district: 'జిల్లా',
        state: 'రాష్ట్రం',
        location: 'స్థానం',
        submitrequest: 'అభ్యర్థన సమర్పించండి',
        submitting: 'సమర్పిస్తోంది…',
        requestsubmittedsuccessfully: 'అభ్యర్థన విజయంగా సమర్పించబడింది! మేము త్వరలో జవాబిస్తాం.',

        // Responses
        viewallresponses: 'అన్ని స్పందనలు చూడండి',
        allresponses: 'అన్ని స్పందనలు',
        expertemail: 'నిపుణుని ఇమెయిల్',
        responsedetails: 'స్పందన వివరాలు',
        noqueriesyet: 'ఇంకా ఏ ప్రశ్నా సమర్పించబడలేదు.',
        awaitingresponse: 'నిపుణుని స్పందన కోసం వేచి ఉంది…',
        yourquery: 'మీ ప్రశ్న',
        expertresponse: 'నిపుణుని స్పందన',

        // Loans
        viewallloans: 'అన్ని రుణాలు చూడండి',
        searchloans: 'రుణాలు వెతుకు…',
        sortbyloantype: 'రుణ రకం ద్వారా క్రమబద్ధీకరించు',
        sortbyinterestrate: 'వడ్డీ రేటు ద్వారా క్రమబద్ధీకరించు',
        sortbymaxamount: 'గరిష్ట మొత్తం ద్వారా క్రమబద్ధీకరించు',
        allloantypes: 'అన్ని రకాలు',
        default: 'డిఫాల్ట్',
        lowtohigh: 'తక్కువ నుండి ఎక్కువ',
        hightolow: 'ఎక్కువ నుండి తక్కువ',
        loanid: 'రుణ ID',
        interestrate: 'వడ్డీ రేటు',
        maxamount: 'గరిష్ట మొత్తం',
        repaymentperiod: 'తిరిగి చెల్లింపు వ్యవధి',
        months: 'నెలలు',
        applyforloan: 'రుణానికి దరఖాస్తు చేయండి',
        noloansavailable: 'ఇంకా రుణ ఉత్పత్తులు అందుబాటులో లేవు.',
        croploan: 'పంట రుణం',
        equipmentloan: 'పరికరాల రుణం',
        soilimprovement: 'నేల మెరుగుదల',

        // Loan Application
        applicantname: 'దరఖాస్తుదారు పేరు',
        email: 'ఇమెయిల్',
        contactnumber: 'సంప్రదింపు నంబర్',
        uploaddocuments: 'పత్రాలు అప్‌లోడ్ చేయండి',
        submitapplication: 'దరఖాస్తు సమర్పించండి',
        successfullyapplied: 'దరఖాస్తు విజయంగా సమర్పించబడింది!',
        applyingforloantype: 'రుణ రకానికి దరఖాస్తు చేస్తున్నావు',
        withinterestrate: 'వడ్డీ రేటుతో',
        maximumamountis: 'గరిష్ట మొత్తం',
        repaymentperiodis: 'తిరిగి చెల్లింపు వ్యవధి',

        // Farming Content
        allfarmingcontent: 'అన్ని వ్యవసాయ కంటెంట్',
        explorefarmingcontent: 'వ్యవసాయ కంటెంట్ అన్వేషించు',
        showfull: 'పూర్తిగా చూడు',
        readmore: 'మరింత చదవండి',
        createddate: 'సృష్టించిన తేదీ',
        noarticlesfound: 'వ్యాసాలు కనుగొనబడలేదు.',

        // Sell Goods
        sellyourproduce: 'మీ ఉత్పత్తి అమ్మండి',
        addnewproduct: 'కొత్త జాబితా జోడించు',
        myproducts: 'నా ఉత్పత్తి జాబితాలు',
        productname: 'ఉత్పత్తి పేరు',
        selectcategory: 'వర్గాన్ని ఎంచుకోండి',
        vegetables: 'కూరగాయలు',
        fruits: 'పండ్లు',
        grains: 'ధాన్యాలు',
        dairy: 'డైరీ',
        priceperkg: 'ధర (₹ ప్రతి యూనిట్)',
        availablequantity: 'పరిమాణం',
        productimages: 'ఉత్పత్తి చిత్రాలు (ఐచ్ఛికం)',
        harvestdate: 'పంట తేదీ (ఐచ్ఛికం)',
        kg: 'కిలో',
        price: 'ధర',
        quantity: 'పరిమాణం',
        unit: 'యూనిట్',
        createListing: 'జాబితా సృష్టించు',
        creating: 'సృష్టిస్తోంది…',
        remove: 'తొలగించు',
        nolistingsyet: 'ఇంకా జాబితాలు లేవు. పైన మీ ఉత్పత్తి జోడించండి!',
    },

    es: {
        // General
        welcome: 'Bienvenido',
        logout: 'Cerrar sesión',
        login: 'Iniciar sesión',
        home: 'Inicio',
        back: 'Atrás',
        cancel: 'Cancelar',
        edit: 'Editar',
        delete: 'Eliminar',
        save: 'Guardar',
        loading: 'Cargando…',
        error: 'Error',
        success: 'Éxito',
        pending: 'Pendiente',
        resolved: 'Resuelto',
        status: 'Estado',
        author: 'Autor',
        category: 'Categoría',
        description: 'Descripción',
        previous: 'Anterior',
        next: 'Siguiente',
        search: 'Buscar',

        // Farmer Home
        welcomefarmer: '¡Bienvenido, Agricultor!',
        farmerinspirationquote: 'El agricultor es la columna vertebral de nuestra economía.',
        quickactions: 'Acciones rápidas',

        // Crop Suggestion
        sendcropsuggestionrequest: 'Enviar solicitud de sugerencia de cultivo',
        croptype: 'Tipo de cultivo',
        requestdetails: 'Detalles de la solicitud',
        district: 'Distrito',
        state: 'Estado',
        location: 'Ubicación',
        submitrequest: 'Enviar solicitud',
        submitting: 'Enviando…',
        requestsubmittedsuccessfully: '¡Solicitud enviada con éxito! Responderemos pronto.',

        // Responses
        viewallresponses: 'Ver todas las respuestas',
        allresponses: 'Todas las respuestas',
        expertemail: 'Correo del experto',
        responsedetails: 'Detalles de la respuesta',
        noqueriesyet: 'Aún no se han enviado consultas.',
        awaitingresponse: 'Esperando respuesta del experto…',
        yourquery: 'Tu consulta',
        expertresponse: 'Respuesta del experto',

        // Loans
        viewallloans: 'Ver todos los préstamos',
        searchloans: 'Buscar préstamos…',
        sortbyloantype: 'Ordenar por tipo de préstamo',
        sortbyinterestrate: 'Ordenar por tasa de interés',
        sortbymaxamount: 'Ordenar por monto máximo',
        allloantypes: 'Todos los tipos',
        default: 'Predeterminado',
        lowtohigh: 'De menor a mayor',
        hightolow: 'De mayor a menor',
        loanid: 'ID de préstamo',
        interestrate: 'Tasa de interés',
        maxamount: 'Monto máximo',
        repaymentperiod: 'Período de pago',
        months: 'meses',
        applyforloan: 'Solicitar préstamo',
        noloansavailable: 'No hay productos de préstamo disponibles aún.',
        croploan: 'Préstamo de cultivo',
        equipmentloan: 'Préstamo de equipo',
        soilimprovement: 'Mejora de suelo',

        // Loan Application
        applicantname: 'Nombre del solicitante',
        email: 'Correo electrónico',
        contactnumber: 'Número de contacto',
        uploaddocuments: 'Subir documentos',
        submitapplication: 'Enviar solicitud',
        successfullyapplied: '¡Solicitud enviada con éxito!',
        applyingforloantype: 'Solicitando préstamo de tipo',
        withinterestrate: 'con tasa de interés',
        maximumamountis: 'El monto máximo es',
        repaymentperiodis: 'El período de pago es',

        // Farming Content
        allfarmingcontent: 'Todo el contenido agrícola',
        explorefarmingcontent: 'Explorar contenido agrícola',
        showfull: 'Ver completo',
        readmore: 'Leer más',
        createddate: 'Fecha de creación',
        noarticlesfound: 'No se encontraron artículos.',

        // Sell Goods
        sellyourproduce: 'Vende tu producción',
        addnewproduct: 'Añadir nueva publicación',
        myproducts: 'Mis publicaciones',
        productname: 'Nombre del producto',
        selectcategory: 'Seleccionar categoría',
        vegetables: 'Verduras',
        fruits: 'Frutas',
        grains: 'Granos',
        dairy: 'Lácteos',
        priceperkg: 'Precio (₹ por unidad)',
        availablequantity: 'Cantidad',
        productimages: 'Imágenes del producto (opcional)',
        harvestdate: 'Fecha de cosecha (opcional)',
        kg: 'kg',
        price: 'Precio',
        quantity: 'Cantidad',
        unit: 'Unidad',
        createListing: 'Crear publicación',
        creating: 'Creando…',
        remove: 'Eliminar',
        nolistingsyet: '¡Aún no hay publicaciones. Añade tu producción arriba!',
    },
}

export const t = (key, language = 'en') => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key
}

export default t
